# ===============================
# Server Configuration
# ===============================
server.port=8081

# ===============================
# PostgreSQL Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/PetroSpy
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.hibernate.ddl-auto=update
